mac/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include(('shop.urls', 'shop'), namespace='shop' )),   # path to another app yaha par aane ke baad shop.url par rawana kardo, mujhe kuch nahi pata
    path('blog/',include('blog.urls')),
    path('', views.index),

    #re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index,name="home"),
    path("about/", views.about,name="AboutUs"),
    path("contact/", views.contact,name="ContactUs"),
    path("tracker/", views.tracker,name="TrackingStatus"),
    path("search/", views.search,name="Search"),
    path("products/<int:myid>", views.productView,name="ProductView"), # data provided by html when this href is called
    path("checkout/", views.checkout,name="Checkout"),

    # Payment With Razorpay
    path("payment/", views.app_create,name="payment"),
    path("payment/charge/", views.app_charge,name="charge"),

    # Authentication APIs
    path('handleLogout/', views.handleLogout, name='handleLogout'),
    path('myprofile/', views.myprofile,  name="myprofile"),
    path('handleLoginEmail/', views.handleLoginEmail, name='handleLoginEmail'),
    path('changeEmail/', views.changeEmail, name='changeEmail'),
    path('register/', views.SignUpView.as_view(), name='register'),

]

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from .managers import UserManager
from django.core.validators import RegexValidator
import datetime

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=255,blank=True, null=True, default=None)
    phone_regex = RegexValidator( regex = r'^\+?1?\d{10}$',message = "Phone number must be entered in proper format in 10 digits.")#the format: '+999999999'. Up to 14 digits allowed.")
    user_phone = models.CharField(validators = [phone_regex], max_length=15)
    user_email = models.EmailField('email address', unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_email_verified = models.BooleanField(default=False)
    is_premium_activated = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.user_email

# Create your models here.
# create a database schema structure
class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300)
    pub_date = models.DateField()
    image = models.ImageField(upload_to="shop/images", default="")

    # function so that in database items added to database are shown with their name
    def __str__(self):
        return self.product_name


class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.name


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000)
    name = models.CharField(max_length=90)
    email = models.CharField(max_length=111)
    address = models.CharField(max_length=111)
    city = models.CharField(max_length=111)
    state = models.CharField(max_length=111)
    zip_code = models.CharField(max_length=111)
    phone = models.CharField(max_length=111, default="")
    amount = models.IntegerField(default=0)
    razorpayid = models.CharField(max_length=255,default="")
    razorpaypaymentid = models.CharField(max_length=255,default="")
    razorpaysignature = models.CharField(max_length=255, default="")


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:7] + "..."

shop/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User
from django import forms


class UserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('user_phone',)


class UserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('user_phone',)

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'user_email', 
            'user_name', 
            'user_phone',
            'password1', 
            'password2', 
            ]

shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product, Contact, Orders, OrderUpdate
from math import ceil
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from mac import settings

from django.views.generic import CreateView
from .forms import SignUpForm
from django.urls import reverse_lazy

# payment
import razorpay
razorpay_client = razorpay.Client(auth=(settings.razorpay_id, settings.razorpay_account_id))


# Create your views here.
def index(request):
    # products = Product.objects.all()
    # print(products)
    # n = len(products)
    # nSlides = n//4 + ceil((n/4)-(n//4))    # formula designed to get no. of slides according to no. of products in database
    allProds=[]
    catprods = Product.objects.values('category','id')
    cats = {item['category'] for item in catprods}    # filters unique category out of query set as unique keys 
    for cat in cats:
        prod = Product.objects.filter(category=cat)
        n=len(prod)
        # print(type(prod))
        # print(prod[0].category)   # category is attribute of prod[0] like <Product: watch>.category
        #print(<Product: watch>.category)
        nSlides = nSlides = n//4 + ceil((n/4)-(n//4))
        allProds.append([prod, range(1,nSlides),nSlides])
    #params = {'no_of_slides':nSlides,'range':range(1,nSlides),'product': products}
    # allProds = [[products, range(1, nSlides), nSlides],
    #              [products, range(1, nSlides), nSlides]]
    params = {'allProds': allProds}
    return render(request,'shop/index.html',params)
def about(request):
    return render(request,'shop/about.html')

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)   # saving in dataset just like by using python as in shell
        contact.save()
        return render(request, 'shop/contact.html', {'query': contact.name})
        # if 'name' in request.POST:
        #     q = request.POST['name']
        #     return render(request, 'shop/contact.html', {'query': q})
    return render(request, 'shop/contact.html')
def tracker(request):
    if request.method == "POST":
        orderId = request.POST.get('orderId', '')
        email = request.POST.get('email', '')
        try:
            order = Orders.objects.filter(order_id=orderId, email=email)
            if len(order) > 0:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                for item in update:
                    updates.append({'text': item.update_desc, 'time': item.timestamp})
                    # print(order[0].items_json)
                    response = json.dumps([updates,order[0].items_json], default=str)
                return HttpResponse(response)      #here sending the json to ajax
            else:
                return HttpResponse('{}')
        except Exception as e:
            return HttpResponse('{}')

    return render(request, 'shop/tracker.html')
def search(request):
    return render(request, 'shop/search.html')
def productView(request,myid):
    # Fetch the product using id
    product = Product.objects.filter(id=myid)
    return render(request, 'shop/prodView.html',{'product':product[0]})     # product ek list hai jisme kewal ek hi item hai koi id sabki unique hai
def checkout(request):
    return render(request, 'shop/checkout.html')

# Payment Method through Razorpay
def app_create(request):
    if request.method == "POST":
        items_json = request.POST.get('itemsJson','')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address', '') + " " + request.POST.get('address2','')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        phone = request.POST.get('phone', '')
        order_amount = int(request.POST.get('formprice', ''))
        order_currency = 'INR'
        order_receipt = 'order_rcptid_11'
        notes = {'Shipping address': address}
        razorpay_order = razorpay_client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes, payment_capture='0'))
        print(razorpay_order['id'])
        order = Orders(items_json=items_json, name=name, email=email,address=address,city=city,state=state,zip_code=zip_code, phone=phone, amount=order_amount, razorpayid=razorpay_order['id'])   # saving in dataset just like by using python as in shell
        order.save()
        return render(request, 'shop/payment.html', {'order_id': razorpay_order['id'], 'cname': name, 'cemail': email,'cphone':phone})
        # ,{'order_id': order.order_id, 'amt': order_amount}

def app_charge(request):
    if request.method == "POST":
        try:
            payment_id = request.POST.get('razorpay_payment_id', '')
            order_id = request.POST.get('razorpay_order_id','')
            signature = request.POST.get('razorpay_signature','')
            params_dict = { 
            'razorpay_order_id': order_id, 
            'razorpay_payment_id': payment_id,
            'razorpay_signature': signature
            }
            order_db = Orders.objects.get(razorpayid=order_id)
            order_db.razorpaypaymentid = payment_id
            order_db.razorpaysignature = signature
            order_db.save()
            result = razorpay_client.utility.verify_payment_signature(params_dict)
            print(result)
            if result==None:
                amount = order_db.amount
                try:
                    razorpay_client.payment.capture(payment_id, amount)
                    update = OrderUpdate(order_id=order_db.order_id, update_desc="The order has been placed")
                    update.save()
                    thank = True
                    id = request.POST.get('shopping_order_id','')
                    params = {'thank': thank, 'id': id}
                    # response = json.dumps(razorpay_client.payment.fetch(payment_id))
                    return render(request, 'shop/checkout.html', params)
                except:
                    update = OrderUpdate(order_id=order_db.order_id, update_desc="Payment is unsuccessful")
                    update.save()
                    thank =  False
                    return render(request, 'shop/checkout.html', {'thank': thank})
            else:
                update = OrderUpdate(order_id=order_db.order_id, update_desc="Payment is unsuccessful")
                update.save()
                thank =  False
                return render(request, 'shop/checkout.html', {'thank': thank})
        except:
            update = OrderUpdate(order_id=order_db.order_id, update_desc="Payment is unsuccessful")
            update.save()
            thank =  False
            return render(request, 'shop/checkout.html', {'thank': thank})



def myprofile(request):
    return render(request, 'shop/myprofile.html')

def handleLoginEmail(request):
    if request.method == 'POST':
        # Get the post parameters
        loginemail = request.POST.get('loginemail', '')
        loginpass = request.POST.get('loginpass', '')
        user = authenticate(user_email=loginemail, password=loginpass)
        print(user)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect('shop:home')
        else:
            messages.error(request, "Incorrect Credentials")
            return redirect('shop:home')
    return render(request, 'shop/loginemail.html')

def changeEmail(request):
    if request.method == 'POST':
        print(request.POST.get('email',''))
        if request.user.is_anonymous:
            print("hello")
            return HttpResponse("You are not loginned") 
        client = request.user
        email = request.POST.get('email','')
        if email:
            client.user_email = email
            client.save()
        else:
            return HttpResponse("Please enter new email address")
        print(request.user)
        messages.success(request,"Successfully Changed the email")
        return redirect('shop:home')
    print("hello")
    return render(request, "shop/changeemail.html")

def handleLogout(request):
    logout(request)
    messages.success(request,"Successfully Logged Out")
    # to land on same page where logged out
    # path=path[0:-1]
    # path="/"+path
    return redirect('shop:home')

class SignUpView(CreateView):
    form_class = SignUpForm    # in signupform there is inbuilt create user function so no need for create_user in managers.py
    success_url = reverse_lazy('shop:handleLoginEmail')
    template_name = 'shop/register.html'

shop/templates/shop/about.html
{% extends 'shop/basic.html' %}       <!-- for template inheritence from basic -->

{% block title%} About Us{% endblock %}
{% block body %}




<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">My Awesome Cart!</h1>
      <p>My Awesome Cart Pvt Ltd. is an Indian electronic commerce company based in Bengaluru, India. Founded by Sachin Bansal and Binny Bansal in 2007, the company initially focused on book sales, before expanding into other product categories such as consumer electronics, fashion, and lifestyle products.

The service competes primarily with Amazon' s Indian subsidiary, and the domestic rival Snapdeal.[5][6] as of March 2017, Flipkart held a 39.5% market share of India's e-commerce industry.[7] Flipkart is significantly dominant in the sale of apparel (a position that was bolstered by its acquisitions of Myntra and Jabong.com), and was described as being "neck and neck" with Amazon in the sale of electronics and mobile phones.[8] Flipkart also owns PhonePe, a mobile payments service based on the Unified Payments Interface (UPI).

In August 2018, U.S.-based retail chain Walmart acquired a 77% controlling stake in Flipkart for US$16 billion, valuing it at $22 billion.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>





{% endblock %}

shop/templates/shop/basic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
     <style>
       {% block css %} {% endblock %}
  </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/shop">XYZ Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/shop">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/shop/about">About Us</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/shop/tracker">Tracker</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/shop/contact">Contact Us</a>
      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="btn-group">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-expanded="false">
    Account
  </button>
  <ul class="dropdown-menu dropdown-menu-lg-right">
    {% if user.is_authenticated %}
    <li><button class="dropdown-item" type="button"><a href="/shop/myprofile/">My Profile</a></button></li>
    <li><button class="dropdown-item" type="button"><a href="/shop/handleLogout/">Logout</a></button></li>
    {% else %}
    <li><button class="dropdown-item" type="button"><a href="/shop/handleLoginEmail/">Sign In</a></button></li>
    <li><button class="dropdown-item" type="button"><a href="/shop/register/">Register</a></button></li>
    {% endif %}
  </ul>
</div>
    <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">


  Cart(<span id="cart">0</span>)
</button>
  </div>
</nav>
{% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible " runat="server" id="modalEditError" visible="false">
            <button class="close" type="button" data-dismiss="alert">×</button>
            <strong>Message: </strong>{{message}} <div id="Div2" runat="server"></div>
        </div>
        {% endfor %}
        {% endif %}
  {% block body %} {% endblock %}

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block js%}  {% endblock %}   <!-- external javascript added after jquery so that jquery can also be used -->
  </body>
</html>

shop/templates/shop/changeemail.html
{% extends 'shop/basic.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block css %}


{% endblock %}

{% block body %}
<div class="container">
<form action="/shop/changeEmail/" method="post">{% csrf_token %}
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email"
            placeholder="Enter Your Email" required>
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>
{% endblock %}

shop/templates/shop/contact.html
{% extends 'shop/basic.html' %}

{% block title%} Contact Us - My Awesome Cart{% endblock %}
{% block body %}
<div class="container my-3">
    <h3>Contact Us</h3>
    <form action="/shop/contact/" method="post">{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name='name' placeholder="Enter Your Name">
  </div>
  <div class="form-group">
    <label for="name">Email</label>
    <input type="email" class="form-control" id="email" name='email' placeholder="Enter Your Email">
  </div>

    <div class="form-group">
    <label for="name">Phone</label>
    <input type="tel" class="form-control" id="phone" name='phone' placeholder="Enter Your Phone Number">
  </div>


   <div class="form-group">
    <label for="desc">How May We Help You?</label>
    <textarea class="form-control" id="desc" name='desc' rows="3"></textarea>
  </div>
        <button type="submit" class="btn btn-success">Submit</button>
</form>
{% if query %}
Thank You, {{ query }} For Contacting Us<br/>
{% endif %}


</div>
{% endblock %}

shop/templates/shop/loginemail.html
{% extends 'shop/basic.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block css %}


{% endblock %}

{% block body %}

<div class="container">
<form class="px-4 py-3" method="post" action="/shop/handleLoginEmail/" id="loginform">{% csrf_token %}
    <div class="form-group">
        <label for="loginemail">Email</label>
        <input type="email" class="form-control" id="loginemail" name="loginemail"
            placeholder="Enter Your Email" required>
    </div>
    <div class="form-group">
        <label for="loginpass">Password</label>
        <input type="password" class="form-control" id="loginpass" name="loginpass"
            placeholder="Password" required>
    </div>
    <div>
        If new user then<span>
            <a href="{% url "shop:register" %}">Sign Up</a></span>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="dropdownCheck">
            <label class="form-check-label" for="dropdownCheck">
                Remember me
            </label>
        </div>
    </div>
    <button type="submit" id="loginbutton" class="btn btn-primary">Sign in</button>
</form>


</div>
{% endblock %}

shop/templates/shop/myprofile.html
{% extends 'shop/basic.html' %}
{% load static %}
{% block title %}
My Profile
{% endblock %}
{% block css %}


{% endblock %}

{% block body %}
<div class="container">
<h1>Welcome</h1>
<a class="btn btn-primary" href="{% url "shop:changeEmail" %}">Change Email</a>
</div>
{% endblock %}

shop/templates/shop/payment.html
  
<html>
<head lang="en">
    <meta charset="utf-8">
</head>
<body>
    Pay Here
 <form action="charge/" method="POST"> {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_N8qzOUbSVfTEex" // Enter the Key ID generated from the Dashboard
    data-currency="INR"
    data-order_id="{{order_id}}"//This is a sample Order ID. Pass the `id` obtained in the response of the previous step.
    data-buttontext="Pay with Razorpay"
    data-name="XYZ Company"
    data-description="Test transaction"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{cname}}"
    data-prefill.email="{{cemail}}"
    data-prefill.contact="{{cphone}}"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
</body>
</html

shop/templates/shop/register.html
<!doctype html>
<html lang="en">
{% load static %}
{% load myfilters %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

  <!-- Favicons -->


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
</head>

<body>
  <div class="container">
    <main class="form-signin">
      <form method="POST" onsubmit="{% url "shop:register" %}">{% csrf_token %}
        <h1 class="brand-name">XYZ Ecommerce</h1>
        <h1 class="h3 mb-3 font-weight-normal">Please Sign Up</h1>
        {{ form.non_field_errors }}
        <label for="id_user_email" class="login-labels">Email Address*</label>
        <!-- <input type="email" name="user_email" class="form-control" autofocus autocapitalize="none" maxlength="254" required id="id_user_email"> -->
        {{ form.user_email|addclass:'form-control'|addplaceholder:'Email Address' }}
        {{ form.user_email.errors }}
        <label for="id_user_name" class="login-labels">Your Name*</label>
        {{ form.user_name|addclass:'form-control'|addplaceholder:'Your Name' }}
        {{ form.user_name.errors }}
        <label for="id_user_phone" class="login-labels">Phone Number*</label>
          {{ form.user_phone|addclass:'form-control'|addplaceholder:'Phone Number' }}
        {{ form.user_phone.errors }}
        <label for="id_password1" class="login-labels">Password*</label>
        {{ form.password1|addclass:'form-control'|addplaceholder:'Password' }}
        {{ form.password1.errors }}
        <label for="id_password2" class="login-labels">Password Confirmation*</label>
        {{ form.password2|addclass:'form-control'|addplaceholder:'Password' }}
        {{ form.password2.errors }}
        <p class="login-labels">Exisiting User? <a href="{% url "shop:handleLoginEmail" %}">Sign In</a></p>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
      </form>
    </main>
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
      integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
      crossorigin="anonymous"></script>
    <div>
</body>

</html>

shop/templates/shop/search.html
{% extends 'shop/basic.html' %}

{% block title%} Search Results - My Awesome Cart{% endblock %}
{% block body %} This is our checkout page {% endblock %}